package br.edu.planodesaude.GUI.main;

import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.ImageIcon;

import br.edu.planodesaude.GUI.estabelecimento.AlterarStatusEstabelecimento;
import br.edu.planodesaude.GUI.estabelecimento.AtualizarEstabelecimento;
import br.edu.planodesaude.GUI.estabelecimento.CadastrarEstabelecimento;
import br.edu.planodesaude.GUI.fatura.EmitirFaturaEstabelecimento;
import br.edu.planodesaude.GUI.fatura.EmitirFaturaUsuario;
import br.edu.planodesaude.GUI.medico.AlterarStatusMedico;
import br.edu.planodesaude.GUI.medico.AtualizarMedico;
import br.edu.planodesaude.GUI.medico.CadastrarMedico;
import br.edu.planodesaude.GUI.pesquisa.PesquisarPorData;
import br.edu.planodesaude.GUI.pesquisa.PesquisarPorEspecialidade;
import br.edu.planodesaude.GUI.pesquisa.PesquisarPorMedico;
import br.edu.planodesaude.GUI.pesquisa.PesquisarPorPaciente;
import br.edu.planodesaude.GUI.procedimento.AtualizarProcedimento;
import br.edu.planodesaude.GUI.procedimento.CadastrarEspecialidade;
import br.edu.planodesaude.GUI.procedimento.CadastrarProcedimento;
import br.edu.planodesaude.GUI.procedimento.MarcarCirurgia;
import br.edu.planodesaude.GUI.procedimento.MarcarConsulta;
import br.edu.planodesaude.GUI.usuario.AlterarStatusUsuario;
import br.edu.planodesaude.GUI.usuario.AtualizarUsuario;
import br.edu.planodesaude.GUI.usuario.CadastrarUsuario;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gustavo
 */
public class TelaPrincipal extends javax.swing.JFrame {
	
    public TelaPrincipal() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
        setTitle("Horse Health");
        setExtendedState(MAXIMIZED_BOTH);
    }

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
    	/*Adicionando uma imagem ao background da JDesktopPane*/
        jDesktopPane1 = new DecoratedDesktopPane("background.jpg");
       
        menuPrincipalJMenuBar = new javax.swing.JMenuBar();
        cadastrarJMenu = new javax.swing.JMenu();
        cMedicoJMenuItem = new javax.swing.JMenuItem();
        cEstabelecimentoJMenuItem = new javax.swing.JMenuItem();
        cUsuarioJMenuItem = new javax.swing.JMenuItem();
        cProcedimentoJMenuItem = new javax.swing.JMenuItem();
        cEspecialidadeJMenuItem = new javax.swing.JMenuItem();
        alterarJMenu = new javax.swing.JMenu();
        aMedicoJMenuItem = new javax.swing.JMenuItem();
        aEstabelecimentoJMenuItem = new javax.swing.JMenuItem();
        aUsuarioJMenuItem = new javax.swing.JMenuItem();
        aProcedimentoJMenuItem = new javax.swing.JMenuItem();
        mudarStatusJMenu = new javax.swing.JMenu();
        msMedicoJMenuItem = new javax.swing.JMenuItem();
        msEstabelecimentoJMenuItem = new javax.swing.JMenuItem();
        msUsuarioJMenuItem = new javax.swing.JMenuItem();
        marcarProcedimentoJMenu = new javax.swing.JMenu();
        mpConsultaJMenuItem = new javax.swing.JMenuItem();
        mpCirurgiaJMenuItem = new javax.swing.JMenuItem();
        pesquisarProcedimentoJMenu = new javax.swing.JMenu();
        ppDataJMenuItem = new javax.swing.JMenuItem();
        ppMedicoJMenuItem = new javax.swing.JMenuItem();
        ppEspecialidadeJMenuItem = new javax.swing.JMenuItem();
        ppPacienteJMenuItem = new javax.swing.JMenuItem();
        emitirFaturaJMenu = new javax.swing.JMenu();
        efUsuarioJMenuItem = new javax.swing.JMenuItem();
        efEstabelecimentoJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastrarJMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("add.png"))); // NOI18N
        cadastrarJMenu.setText("Cadastrar");

        cMedicoJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("award_star_add.png"))); // NOI18N
        cMedicoJMenuItem.setText("Médico");
        cMedicoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMedicoJMenuItemActionPerformed(evt);
            }
        });
        cadastrarJMenu.add(cMedicoJMenuItem);

        cEstabelecimentoJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("building_add.png"))); // NOI18N
        cEstabelecimentoJMenuItem.setText("Estabelecimento");
        cEstabelecimentoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEstabelecimentoJMenuItemActionPerformed(evt);
            }
        });
        cadastrarJMenu.add(cEstabelecimentoJMenuItem);

        cUsuarioJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("group_add.png"))); // NOI18N
        cUsuarioJMenuItem.setText("Usuário");
        cUsuarioJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUsuarioJMenuItemActionPerformed(evt);
            }
        });
        cadastrarJMenu.add(cUsuarioJMenuItem);

        cProcedimentoJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("application_form_add.png"))); // NOI18N
        cProcedimentoJMenuItem.setText("Procedimento");
        cProcedimentoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cProcedimentoJMenuItemActionPerformed(evt);
            }
        });
        cadastrarJMenu.add(cProcedimentoJMenuItem);

        cEspecialidadeJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("lightbulb_add.png"))); // NOI18N
        cEspecialidadeJMenuItem.setText("Especialidade");
        cEspecialidadeJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEspecialidadeJMenuItemActionPerformed(evt);
            }
        });
        cadastrarJMenu.add(cEspecialidadeJMenuItem);

        menuPrincipalJMenuBar.add(cadastrarJMenu);

        alterarJMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("accept.png"))); // NOI18N
        alterarJMenu.setText("Alterar");

        aMedicoJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("award_star_add.png"))); // NOI18N
        aMedicoJMenuItem.setText("Médico");
        aMedicoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMedicoJMenuItemActionPerformed(evt);
            }
        });
        alterarJMenu.add(aMedicoJMenuItem);

        aEstabelecimentoJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("building_add.png"))); // NOI18N
        aEstabelecimentoJMenuItem.setText("Estabelecimento");
        aEstabelecimentoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aEstabelecimentoJMenuItemActionPerformed(evt);
            }
        });
        alterarJMenu.add(aEstabelecimentoJMenuItem);

        aUsuarioJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("group_add.png"))); // NOI18N
        aUsuarioJMenuItem.setText("Usuário");
        aUsuarioJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aUsuarioJMenuItemActionPerformed(evt);
            }
        });
        alterarJMenu.add(aUsuarioJMenuItem);

        aProcedimentoJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("application_form_add.png"))); // NOI18N
        aProcedimentoJMenuItem.setText("Procedimento");
        aProcedimentoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aProcedimentoJMenuItemActionPerformed(evt);
            }
        });
        alterarJMenu.add(aProcedimentoJMenuItem);

        menuPrincipalJMenuBar.add(alterarJMenu);

        mudarStatusJMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("delete.png"))); // NOI18N
        mudarStatusJMenu.setText("Mudar Status");

        msMedicoJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("award_star_delete.png"))); // NOI18N
        msMedicoJMenuItem.setText("Médico");
        msMedicoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msMedicoJMenuItemActionPerformed(evt);
            }
        });
        mudarStatusJMenu.add(msMedicoJMenuItem);

        msEstabelecimentoJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("building_delete.png"))); // NOI18N
        msEstabelecimentoJMenuItem.setText("Estabelecimento");
        msEstabelecimentoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msEstabelecimentoJMenuItemActionPerformed(evt);
            }
        });
        mudarStatusJMenu.add(msEstabelecimentoJMenuItem);

        msUsuarioJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("group_delete.png"))); // NOI18N
        msUsuarioJMenuItem.setText("Usuário");
        msUsuarioJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msUsuarioJMenuItemActionPerformed(evt);
            }
        });
        mudarStatusJMenu.add(msUsuarioJMenuItem);

        menuPrincipalJMenuBar.add(mudarStatusJMenu);

        marcarProcedimentoJMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("book_add.png"))); // NOI18N
        marcarProcedimentoJMenu.setText("Marcar Procedimento");

        mpConsultaJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("book_add.png"))); // NOI18N
        mpConsultaJMenuItem.setText("Consulta");
        mpConsultaJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpConsultaJMenuItemActionPerformed(evt);
            }
        });
        marcarProcedimentoJMenu.add(mpConsultaJMenuItem);

        mpCirurgiaJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("book_add.png"))); // NOI18N
        mpCirurgiaJMenuItem.setText("Cirurgia");
        mpCirurgiaJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpCirurgiaJMenuItemActionPerformed(evt);
            }
        });
        marcarProcedimentoJMenu.add(mpCirurgiaJMenuItem);

        menuPrincipalJMenuBar.add(marcarProcedimentoJMenu);

        pesquisarProcedimentoJMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("magnifier.png"))); // NOI18N
        pesquisarProcedimentoJMenu.setText("Pesquisar Procedimento ");

        ppDataJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("date.png"))); // NOI18N
        ppDataJMenuItem.setText("por Data");
        ppDataJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppDataJMenuItemActionPerformed(evt);
            }
        });
        pesquisarProcedimentoJMenu.add(ppDataJMenuItem);

        ppMedicoJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("award_star_gold_3.png"))); // NOI18N
        ppMedicoJMenuItem.setText("por Médico");
        ppMedicoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppMedicoJMenuItemActionPerformed(evt);
            }
        });
        pesquisarProcedimentoJMenu.add(ppMedicoJMenuItem);

        ppEspecialidadeJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("lightbulb.png"))); // NOI18N
        ppEspecialidadeJMenuItem.setText("por Especialidade");
        ppEspecialidadeJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppEspecialidadeJMenuItemActionPerformed(evt);
            }
        });
        pesquisarProcedimentoJMenu.add(ppEspecialidadeJMenuItem);

        ppPacienteJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("group.png"))); // NOI18N
        ppPacienteJMenuItem.setText("por Paciente");
        ppPacienteJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppPacienteJMenuItemActionPerformed(evt);
            }
        });
        pesquisarProcedimentoJMenu.add(ppPacienteJMenuItem);

        menuPrincipalJMenuBar.add(pesquisarProcedimentoJMenu);

        emitirFaturaJMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("book_open.png"))); // NOI18N
        emitirFaturaJMenu.setText("Emitir Fatura");

        efUsuarioJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("group.png"))); // NOI18N
        efUsuarioJMenuItem.setText("do Usuário");
        efUsuarioJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efUsuarioJMenuItemActionPerformed(evt);
            }
        });
        emitirFaturaJMenu.add(efUsuarioJMenuItem);

        efEstabelecimentoJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("building.png"))); // NOI18N
        efEstabelecimentoJMenuItem.setText("do Estabelecimento");
        efEstabelecimentoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efEstabelecimentoJMenuItemActionPerformed(evt);
            }
        });
        emitirFaturaJMenu.add(efEstabelecimentoJMenuItem);

        menuPrincipalJMenuBar.add(emitirFaturaJMenu);

        setJMenuBar(menuPrincipalJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void cMedicoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        jDesktopPane1.add((Component)new CadastrarMedico());
    }                                                

    private void cEstabelecimentoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                          
    	jDesktopPane1.add((Component)new CadastrarEstabelecimento());
    }                                                         

    private void cUsuarioJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    	jDesktopPane1.add((Component)new CadastrarUsuario());
    }                                                 

    private void cProcedimentoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                       
    	jDesktopPane1.add((Component)new CadastrarProcedimento());
    }                                                      

    private void cEspecialidadeJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                        
    	jDesktopPane1.add((Component)new CadastrarEspecialidade());
    }                                                       

    private void aMedicoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	jDesktopPane1.add((Component)new AtualizarMedico());
    }                                                

    private void aEstabelecimentoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                          
    	jDesktopPane1.add((Component)new AtualizarEstabelecimento());
    }                                                         

    private void aUsuarioJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        jDesktopPane1.add((Component)new AtualizarUsuario());
    }                                                 

    private void aProcedimentoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                       
    	jDesktopPane1.add((Component)new AtualizarProcedimento());
    }                                                      

    private void msMedicoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        jDesktopPane1.add((Component) new AlterarStatusMedico());
    }                                                 

    private void msEstabelecimentoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                           
    	jDesktopPane1.add((Component) new AlterarStatusEstabelecimento());
    }                                                          

    private void msUsuarioJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        jDesktopPane1.add((Component) new AlterarStatusUsuario());
    }                                                  

    private void mpConsultaJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                    
    	jDesktopPane1.add((Component) new MarcarConsulta());
    }                                                   

    private void mpCirurgiaJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                    
    	jDesktopPane1.add((Component) new MarcarCirurgia());
    }                                                   

    private void ppDataJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                
    	jDesktopPane1.add((Component) new PesquisarPorData());
    }                                               

    private void ppMedicoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    	jDesktopPane1.add((Component) new PesquisarPorMedico());
    }                                                 

    private void ppEspecialidadeJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                         
    	jDesktopPane1.add((Component) new PesquisarPorEspecialidade());
    }                                                        

    private void ppPacienteJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        jDesktopPane1.add((Component) new PesquisarPorPaciente());
    }                                                   

    private void efUsuarioJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                   
    	jDesktopPane1.add((Component) new EmitirFaturaUsuario());
    }                                                  

    private void efEstabelecimentoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        jDesktopPane1.add((Component) new EmitirFaturaEstabelecimento());
    }                                                          

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem aEstabelecimentoJMenuItem;
    private javax.swing.JMenuItem aMedicoJMenuItem;
    private javax.swing.JMenuItem aProcedimentoJMenuItem;
    private javax.swing.JMenuItem aUsuarioJMenuItem;
    private javax.swing.JMenu alterarJMenu;
    private javax.swing.JMenuItem cEspecialidadeJMenuItem;
    private javax.swing.JMenuItem cEstabelecimentoJMenuItem;
    private javax.swing.JMenuItem cMedicoJMenuItem;
    private javax.swing.JMenuItem cProcedimentoJMenuItem;
    private javax.swing.JMenuItem cUsuarioJMenuItem;
    private javax.swing.JMenu cadastrarJMenu;
    private javax.swing.JMenuItem efEstabelecimentoJMenuItem;
    private javax.swing.JMenuItem efUsuarioJMenuItem;
    private javax.swing.JMenu emitirFaturaJMenu;
    private DecoratedDesktopPane jDesktopPane1;
    private javax.swing.JMenu marcarProcedimentoJMenu;
    private javax.swing.JMenuBar menuPrincipalJMenuBar;
    private javax.swing.JMenuItem mpCirurgiaJMenuItem;
    private javax.swing.JMenuItem mpConsultaJMenuItem;
    private javax.swing.JMenuItem msEstabelecimentoJMenuItem;
    private javax.swing.JMenuItem msMedicoJMenuItem;
    private javax.swing.JMenuItem msUsuarioJMenuItem;
    private javax.swing.JMenu mudarStatusJMenu;
    private javax.swing.JMenu pesquisarProcedimentoJMenu;
    private javax.swing.JMenuItem ppDataJMenuItem;
    private javax.swing.JMenuItem ppEspecialidadeJMenuItem;
    private javax.swing.JMenuItem ppMedicoJMenuItem;
    private javax.swing.JMenuItem ppPacienteJMenuItem;
    // End of variables declaration                   
}
