package br.edu.planodesaude.GUI.fatura;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystemException;
import java.util.EnumSet;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import br.edu.planodesaude.controle.Faturadora;
import br.edu.planodesaude.controle.Pesquisadora;
import br.edu.planodesaude.dominio.Usuario;
import br.edu.planodesaude.exceptions.InvoiceException;
import br.edu.planodesaude.exceptions.SearchException;
import br.edu.planodesaude.util.Conexao;
import br.edu.planodesaude.util.Formatadora;
import br.edu.planodesaude.util.GeradorPDF;
import br.edu.planodesaude.util.Mes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gustavo
 */
public class EmitirFaturaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmitirFaturaUsuario
     */
    public EmitirFaturaUsuario() {
    	setTitle("Emitir Fatura para Usuário");
    	setVisible(true);
    	setClosable(true);
    	setMaximizable(true);
        initComponents();
        initAnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">   
    private void initAnos(){
    	DefaultComboBoxModel model = new DefaultComboBoxModel();
    	for(int ano = 1990; ano <= 2100; ano++){
    		model.addElement(ano);
    	}
    	anoJComboBox.setModel(model);
    }
    private void initComponents() {

        cpfJLabel = new javax.swing.JLabel();
        cpfJFormattedTextField = new javax.swing.JFormattedTextField();
        mesJComboBox = new javax.swing.JComboBox();
        mesJLabel = new javax.swing.JLabel();
        anoJLabel = new javax.swing.JLabel();
        anoJComboBox = new javax.swing.JComboBox();
        buscarJButton = new javax.swing.JButton();
        nomeJLabel = new javax.swing.JLabel();
        nomeJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoJTextArea = new javax.swing.JTextArea();
        emitirFaturaJButton = new javax.swing.JButton();
        salvarJButton = new javax.swing.JButton();
        
        resultadoJTextArea.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cpfJLabel.setText("CPF");

        try {
            cpfJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        mesJComboBox.setModel(new javax.swing.DefaultComboBoxModel(EnumSet.range(Mes.JANEIRO, Mes.DEZEMBRO).toArray()));

        mesJLabel.setText("Mês");

        anoJLabel.setText("Ano");

        buscarJButton.setText("Buscar");
        buscarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarJButtonActionPerformed(evt);
            }
        });

        nomeJLabel.setText("Nome");

        resultadoJTextArea.setColumns(20);
        resultadoJTextArea.setRows(5);
        jScrollPane1.setViewportView(resultadoJTextArea);

        emitirFaturaJButton.setText("Emitir Fatura");
        emitirFaturaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emitirFaturaJButtonActionPerformed(evt);
            }
        });

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nomeJLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(nomeJTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cpfJLabel)
                                        .addGap(36, 36, 36)
                                        .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buscarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mesJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mesJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(anoJLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(anoJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(emitirFaturaJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mesJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mesJLabel)
                        .addComponent(anoJLabel)
                        .addComponent(anoJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarJButton))
                    .addComponent(cpfJLabel))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeJLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emitirFaturaJButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(270, 81, 812, 525);
    }// </editor-fold>                        
    private Usuario us;
    private void buscarJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	if(cpfJFormattedTextField.getText().equals("   .   .   -  ")){
    		JOptionPane.showMessageDialog(null, "Informe o CPF", "Alerta!", JOptionPane.WARNING_MESSAGE);
    	}else{
    		try{
    			us = new Pesquisadora().pesquisarUsuario(cpfJFormattedTextField.getText());
    			nomeJTextField.setText(us.getNome());
    			cpfJFormattedTextField.setEditable(false);
    		}catch(SearchException sex){
    			JOptionPane.showMessageDialog(null, sex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    }     
    
    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt){
    	if(!resultadoJTextArea.getText().equals("")){
    		File f = null;
    		int ans = JOptionPane.NO_OPTION;
    		try{
    			f = GeradorPDF.createDocument(resultadoJTextArea.getText());
    			ans = JOptionPane.showConfirmDialog(null,"Deseja abrir o arquivo?", "Ver ou não ver", JOptionPane.INFORMATION_MESSAGE);
    		}catch(FileSystemException fsex){
    			JOptionPane.showMessageDialog(null, fsex.getMessage(), "Erro", JOptionPane.INFORMATION_MESSAGE);
    		}
    		if(ans == JOptionPane.YES_OPTION){
    			try {
					Desktop.getDesktop().open(f);
				} catch (IOException ioe) {
					JOptionPane.showMessageDialog(null, ioe.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
				}
    		}
    	}else{
    		if(cpfJFormattedTextField.getText().equals("   .   .   -  "))
    			JOptionPane.showMessageDialog(null, "Informe o CPF", "Alerta!", JOptionPane.WARNING_MESSAGE);
    		else
    			JOptionPane.showMessageDialog(null, "Clique em emitir fatura primeiro", "Alerta!", JOptionPane.WARNING_MESSAGE);
    	}
    }

    private void emitirFaturaJButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	if(cpfJFormattedTextField.getText().equals("   .   .   -  ")){
    		JOptionPane.showMessageDialog(null, "Informe o CPF", "Alerta!", JOptionPane.WARNING_MESSAGE);
    	}else{
    		try{
    			Faturadora fat = new Faturadora();
    			String data = String.format("%s/%2d", anoJComboBox.getSelectedItem().toString(), ((Mes)mesJComboBox.getSelectedItem()).getValor());
    			String result = fat.faturaMensalUsuario(cpfJFormattedTextField.getText(), data);
    			resultadoJTextArea.setText(result);
    			resultadoJTextArea.setEditable(false);
    		}catch(InvoiceException iex){
    			JOptionPane.showMessageDialog(null, iex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    }                                                   

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmitirFaturaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmitirFaturaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmitirFaturaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmitirFaturaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmitirFaturaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox anoJComboBox;
    private javax.swing.JLabel anoJLabel;
    private javax.swing.JButton buscarJButton;
    private javax.swing.JFormattedTextField cpfJFormattedTextField;
    private javax.swing.JLabel cpfJLabel;
    private javax.swing.JButton emitirFaturaJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox mesJComboBox;
    private javax.swing.JLabel mesJLabel;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JTextArea resultadoJTextArea;
    private javax.swing.JButton salvarJButton;
    // End of variables declaration                   
}
