INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(1, "Alergia e Imunologia", "diagnóstico e tratamento das doenças alérgicas e do sistema imunitário");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(2, "Anestesiologia", "estudo da dor e anestesia");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(3, "Angiologia", "é a área da medicina que estuda o tratamento das doenças do aparelho circulatório");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(4, "Cancerologia (oncologia)", "é a especialidade que estuda os tumores malignos ou câncer");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(5, "Cardiologia", "estudo das doenças relacionadas com o coração");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(6, "Cirurgia Cardiovascular", "tratamento cirúrgico de doenças do coração");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(7, "Cirurgia de cabeça e pescoço", "tratamento cirúrgico de doenças da cabeça e do pescoço");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(8, "Cirurgia Plástica", "tratamento para correção das deformidades, má formação ou lesões que comprometem funções dos órgãos através de cirurgia de caráter reparador.");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(9, "Cirurgia Torácica", "atua na cirurgia dos pulmões");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(10, "Dermatologia", "é o estudo da pele e suas doenças");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(11, "Endocrinologia e Metabologia", "é o tratamento das glândulas");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(12, "Endoscopia", "cirurgia abdominal, cirurgia videolaparoscópica e Cirurgia do trauma");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(13, "Gastroenterologia", "É o tratamento do aparelho digestivo");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(14, "Geriatria", "É o estudo das doenças do idoso");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(15, "Mastologia", "Tratamento de doenças da mama");	
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(16, "Infectologia", "Estudo das causas e tratamentos de infecções (causadas por vírus, bacterias e fungos)");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(17, "Ginecologia e obstetrícia", "é o estudo do sistema reprodutor feminino");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(18, "Oftalmologia", "É a parte da medicina que estuda e trata os distúrbios dos olhos");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(19, "Ortopedia e Traumatologia", "É a parte da medicina que estuda e trata as doenças do sistema locomotor e as fraturas");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(20, "Urologia", "É a parte da medicina que estuda e trata cirurgicamente e clinicamente os problemas do sistema urinário e do sistema reprodutor masculino");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(21, "Obstetrícia", "Trata da saúde na reprodução da mulher");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(22, "Odontologia", "Trata da saúde da boca");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(23, "Pediatria", "Trata da saúde na infância");
INSERT INTO ESPECIALIDADE (id_especialidade, nome, descricao) VALUES(24, "Clínica médica", "Trata de doenças não cirúrgicas, não obstetrícias e não ginecológicas");
